### PR TITLE
Adding the align option

### PR DESCRIPTION
**Pull request by Yomguithereal**

### CODE REVIEW

**Comment by glenjamin** [comment]
I think this should be `margin: 0 auto` to avoid cascading into the card perhaps?

**Comment by Yomguithereal** [comment]
I'll trust you on this one. I always forget those things in CSS. If we go this way however, we'll have to handle `left` and `right` also with margin.

**Comment by glenjamin** [comment]
Do you have a sample of a real card you wanted to be centred?

**Comment by Yomguithereal** [comment]
The one with the buttons is a good example. I find it aesthetically weird when it's aligned to the left.

**Comment by glenjamin** [comment]
I've decided not to include this in the library itself, I think it introduces too many edge cases when a simple option is available to consumers without core support.

Notes here: https://github.com/glenjamin/devcards-js/commit/851ff5f6511117c9122e7f8b97797171d2372502

**Comment by Yomguithereal** [comment]
Thanks. Your solution seems better indeed.

**Pull request merged**
